In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [10]:
data.shape

(214, 10)

In [3]:
data["Type"].value_counts()

Type
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64

In [4]:
corr_matrix = data.corr()

In [50]:
corr_matrix["Type"].sort_values(ascending=False)[:3]

Type    1.000000
Al      0.598829
Ba      0.575161
Name: Type, dtype: float64

In [32]:
data_label_1 = data.copy()
data_label_2 = data.copy()
data_label_3 = data.copy()

In [36]:
data_label_1["Type"].unique()

array([1, 2, 3, 5, 6, 7])

In [37]:
data_label_1['Type'] = data_label_1['Type'].apply(lambda x: 1 if x == 1 else 0)

In [39]:
data_label_1["Type"].unique()

array([1, 0])

In [40]:
data_label_2['Type'] = data_label_2['Type'].apply(lambda x: 1 if x == 2 else 0)

In [41]:
data_label_2["Type"].unique()

array([0, 1])

In [42]:
data_label_3['Type'] = data_label_3['Type'].apply(lambda x: 1 if x == 3 else 0)

In [43]:
data_label_3["Type"].unique()

array([0, 1])

In [47]:
corr_matrix_label_1 = data_label_1.corr()
corr_matrix_label_1["Type"].sort_values(ascending=False)[:3]

Type    1.000000
Mg      0.420498
RI      0.081202
Name: Type, dtype: float64

In [48]:
corr_matrix_label_2 = data_label_2.corr()
corr_matrix_label_2["Type"].sort_values(ascending=False)[:3]

Type    1.000000
Fe      0.173502
Mg      0.163772
Name: Type, dtype: float64

In [49]:
corr_matrix_label_3 = data_label_3.corr()
corr_matrix_label_3["Type"].sort_values(ascending=False)[:3]

Type    1.000000
Mg      0.175352
Na      0.010532
Name: Type, dtype: float64

In [51]:
data.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

In [55]:
selected_features = ["Mg", "RI", "Fe", "Na", "Type"]
top_2_corr_for_3_classes = data[selected_features].copy()

In [56]:
top_2_corr_for_3_classes.head()

Mg       RI   Fe     Na  Type
0  4.49  1.52101  0.0  13.64     1
1  3.60  1.51761  0.0  13.89     1
2  3.55  1.51618  0.0  13.53     1
3  3.69  1.51766  0.0  13.21     1
4  3.62  1.51742  0.0  13.27     1

In [57]:
top_2_corr_for_3_classes["Type"].value_counts()

Type
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64